const loginActionTypes = {
    TOGGLE_PASSWORD: 'TOGGLE_PASSWORD',
    SET_EMAIL: 'SET_EMAIL',
    SET_REMEMBER_ME: 'SET_REMEMBER_ME',
    SET_PASSWORD: 'SET_PASSWORD',
    POST_LOGIN_USER : 'POST_LOGIN_USER',
    CHECK_POST_LOGIN_USER : 'CHECK_POST_LOGIN_USER',
}

export default loginActionTypes
