const TOGGLE_PASSWORD = 'TOGGLE_PASSWORD'
const SET_EMAIL = 'SET_EMAIL'
const SET_REMEMBER_ME = 'SET_REMEMBER_ME'
const SET_PASSWORD = 'SET_PASSWORD'
const DO_LOGIN = 'DO_LOGIN'

export { TOGGLE_PASSWORD, SET_PASSWORD, SET_EMAIL, SET_REMEMBER_ME, DO_LOGIN }