const registerActionTypes = {
    SET_NAME: 'SET_NAME',
    SET_EMAIL: 'SET_EMAIL',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_RE_PASSWORD: 'SET_RE_PASSWORD',
    SET_TERMS_AGREEMENT: 'SET_TERMS_AGREEMENT',
    TOGGLE_PASSWORD: 'TOGGLE_PASSWORD',
    TOGGLE_RE_PASSWORD: 'TOGGLE_RE_PASSWORD',
    DO_REGISTER: 'DO_REGISTER',
}


export default registerActionTypes