const registerActionTypes = {
    SET_NAME: 'SET_NAME',
    SET_EMAIL: 'SET_EMAIL',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_RE_PASSWORD: 'SET_RE_PASSWORD',
    SET_TERMS_AGREEMENT: 'SET_TERMS_AGREEMENT',
    TOGGLE_PASSWORD: 'TOGGLE_PASSWORD',
    TOGGLE_RE_PASSWORD: 'TOGGLE_RE_PASSWORD',
    POST_REGISTER_USER : 'POST_REGISTER_USER',
    CHECK_POST_REGISTER_USER : 'CHECK_POST_REGISTER_USER',
}


export default registerActionTypes
