const SET_NAME = 'SET_NAME'
const SET_EMAIL = 'SET_EMAIL'
const SET_PASSWORD = 'SET_PASSWORD'
const SET_RE_PASSWORD = 'SET_RE_PASSWORD'
const SET_TERMS_AGREEMENT = 'SET_TERMS_AGREEMENT'
const TOGGLE_PASSWORD = 'TOGGLE_PASSWORD'
const TOGGLE_RE_PASSWORD = 'TOGGLE_RE_PASSWORD'
const DO_REGISTER = 'DO_REGISTER'

export {SET_NAME, SET_EMAIL, SET_PASSWORD, SET_RE_PASSWORD, SET_TERMS_AGREEMENT, TOGGLE_PASSWORD, TOGGLE_RE_PASSWORD, DO_REGISTER}