const addRecipeActionTypes = {
    SET_RECIPE_TITLE: 'SET_RECIPE_TITLE',
    SET_RECIPE_DESCRIPTION: 'SET_RECIPE_DESCRIPTION',
    SET_RECIPE_MAIN_IMAGE: 'SET_RECIPE_MAIN_IMAGE',
    SET_RECIPE_ADDITIONAL_IMAGES: 'SET_RECIPE_ADDITIONAL_IMAGES',
    SET_RECIPE_CATEGORIES: 'SET_RECIPE_CATEGORIES',
    SET_RECIPE_COOK_TIME: 'SET_RECIPE_COOK_TIME',
    SET_RECIPE_SERVE_PLATE: 'SET_RECIPE_SERVE_PLATE',
    SET_RECIPE_INGREDIENTS: 'SET_RECIPE_INGREDIENTS',
    SET_RECIPE_STEPS: 'SET_RECIPE_STEPS',
    ADD_MORE_INGREDIENTS: 'ADD_MORE_INGREDIENTS',
    ADD_MORE_STEPS: 'ADD_MORE_STEPS',
    REMOVE_RECIPE_MAIN_IMAGE: 'REMOVE_RECIPE_MAIN_IMAGE',
    REMOVE_RECIPE_CATEGORIES: 'REMOVE_RECIPE_CATEGORIES',
    REMOVE_RECIPE_ADDITIONAL_IMAGES: 'REMOVE_RECIPE_ADDITIONAL_IMAGES',
    REMOVE_MORE_INGREDIENTS: 'REMOVE_MORE_INGREDIENTS',
    REMOVE_MORE_STEPS: 'REMOVE_MORE_STEPS',
    TOGGLE_EMOJI_INPUT_DESCRIPTION: 'TOGGLE_EMOJI_INPUT_DESCRIPTION',
    SET_EMOJI_DESCRIPTION: 'SET_EMOJI_DESCRIPTION',
    CHECK_POST_RECIPES: 'CHECK_POST_RECIPES'
}

export default addRecipeActionTypes