const profileActionTypes = {
    SET_INITIAL_PROFILE_DATA: 'SET_INITIAL_PROFILE_DATA',
    SET_NAME: 'SET_NAME',
    CHECK_PUT_UPDATE_PROFILE: 'CHECK_PUT_UPDATE_PROFILE',
    PUT_UPDATE_USER: 'PUT_UPDATE_USER',
    SET_DEFAULT: 'SET_DEFAULT'
}

export default profileActionTypes